name: Run tests

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.sln'

env:
  DOTNET_VERSION: '7.x'

jobs:
  build-and-test:
    name: build-and-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore ./hr/api_tests/api.csproj

      - name: Build
        run: dotnet build ./hr/api_tests/api.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test ./hr/api_tests/api.csproj --no-restore --verbosity normal
